version: '3'

services:
  database:
    image: mysql:latest
    ports:
      - '3306:3306'
    container_name: Animaladoption
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - Animaladoption-disk:/var/lib/mysql
    environment:
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DB: animaladoption

volumes:
  Animaladoption-disk:
